config/routes.rb
Rails.application.routes.draw do

  resources :objective_images
  resources :drag_drops
  resources :subjective_textuals
  resources :objective_textuals
  resources :line_badges do
    collection do
      post :badge_wall_share
    end
  end

  resources :badges
  resources :done_lessons
  get 'admin/index'
  get 'admin/new_token'
  get 'admin/delete_token'

  resources :line_items
  resources :inventories
  get 'store/index'

  resources :items
  resources :characters do
    collection do
      post :addItem
      post :removeItem
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :questions
    end
  end

  resources :lessons
  resources :store

  get 'main/index'

  get 'quiz/index'

  get 'quiz/gerar_quiz'

  get 'quiz/catalog'

  resources :quiz do
    collection do
      post :answer
      post 'answer_question'
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  resources :questions

  root 'main#index'

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
    before_create :generate_access_token

    private

    def generate_access_token
        begin
            self.access_token = SecureRandom.hex
        end while self.class.exists?(access_token: access_token)
    end
end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :User
  validates :name, presence:true

    def add_item(item_name, item_img, item_part)
        if item_part == "helmet"
            self.helmet = item_img
        elsif item_part == "shield"
            self.shield = item_img
        elsif item_part == "weapon"
            self.weapon = item_img
        elsif item_part == "armor"
            self.armor = item_img
        end
    end

    def remove_item(item_part)
        if item_part == "helmet"
            self.helmet = "none"
        elsif item_part == "shield"
            self.shield = "none"
        elsif item_part == "weapon"
            self.weapon = "none"
        elsif item_part == "armor"
            self.armor = "none"
        end
    end

end

app/models/done_lesson.rb
class DoneLesson < ActiveRecord::Base
  belongs_to :Lesson
  belongs_to :Character
end

app/models/drag_drop.rb
class DragDrop < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	private
	def ensure_not_referenced_by_any_line_item
	if line_items.empty?
	return true
	else
	errors.add(:base, 'Line Items present')
	return false
	end
	end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
end

app/models/line_badge.rb
class LineBadge < ActiveRecord::Base
  belongs_to :badge
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :inventory
end

app/models/objective_image.rb
class ObjectiveImage < ActiveRecord::Base
end

app/models/objective_textual.rb
class ObjectiveTextual < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :inventory
	has_many :line_badges
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :timeoutable
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:issuer_url, :issuer_organization, :name, :description, :img_url)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issuer_url %><br>
    <%= f.text_field :issuer_url %>
  </div>
  <div class="field">
    <%= f.label :issuer_organization %><br>
    <%= f.text_field :issuer_organization %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Badges</h1>

<table>
  <thead>
    <tr>
      <th>Issuer url</th>
      <th>Issuer organization</th>
      <th>Name</th>
      <th>Description</th>
      <th>Img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.issuer_url %></td>
        <td><%= badge.issuer_organization %></td>
        <td><%= badge.name %></td>
        <td><%= badge.description %></td>
        <td><%= badge.img_url %></td>
        <td><%= link_to 'Show', badge %></td>
        <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issuer url:</strong>
  <%= @badge.issuer_url %>
</p>

<p>
  <strong>Issuer organization:</strong>
  <%= @badge.issuer_organization %>
</p>

<p>
  <strong>Name:</strong>
  <%= @badge.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @badge.description %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @badge.img_url %>
</p>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>