config/routes.rb
Rails.application.routes.draw do

  resources :objective_images
  resources :drag_drops
  resources :subjective_textuals
  resources :objective_textuals
  resources :line_badges do
    collection do
      post :badge_wall_share
    end
  end

  resources :badges
  resources :done_lessons
  get 'admin/index'
  get 'admin/new_token'
  get 'admin/delete_token'

  resources :line_items
  resources :inventories
  get 'store/index'

  resources :items
  resources :characters do
    collection do
      post :addItem
      post :removeItem
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :questions
    end
  end

  resources :lessons
  resources :store

  get 'main/index'

  get 'quiz/index'

  get 'quiz/gerar_quiz'

  get 'quiz/catalog'

  resources :quiz do
    collection do
      post :answer
      post 'answer_question'
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  resources :questions

  root 'main#index'

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
    before_create :generate_access_token

    private

    def generate_access_token
        begin
            self.access_token = SecureRandom.hex
        end while self.class.exists?(access_token: access_token)
    end
end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :User
  validates :name, presence:true

    def add_item(item_name, item_img, item_part)
        if item_part == "helmet"
            self.helmet = item_img
        elsif item_part == "shield"
            self.shield = item_img
        elsif item_part == "weapon"
            self.weapon = item_img
        elsif item_part == "armor"
            self.armor = item_img
        end
    end

    def remove_item(item_part)
        if item_part == "helmet"
            self.helmet = "none"
        elsif item_part == "shield"
            self.shield = "none"
        elsif item_part == "weapon"
            self.weapon = "none"
        elsif item_part == "armor"
            self.armor = "none"
        end
    end

end

app/models/done_lesson.rb
class DoneLesson < ActiveRecord::Base
  belongs_to :Lesson
  belongs_to :Character
end

app/models/drag_drop.rb
class DragDrop < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	private
	def ensure_not_referenced_by_any_line_item
	if line_items.empty?
	return true
	else
	errors.add(:base, 'Line Items present')
	return false
	end
	end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
end

app/models/line_badge.rb
class LineBadge < ActiveRecord::Base
  belongs_to :badge
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :inventory
end

app/models/objective_image.rb
class ObjectiveImage < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :inventory
	has_many :line_badges
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :timeoutable
end

app/controllers/objective_images_controller.rb
class ObjectiveImagesController < ApplicationController
  before_action :set_objective_image, only: [:show, :edit, :update, :destroy]

  # GET /objective_images
  # GET /objective_images.json
  def index
    @objective_images = ObjectiveImage.all
  end

  # GET /objective_images/1
  # GET /objective_images/1.json
  def show
  end

  # GET /objective_images/new
  def new
    @objective_image = ObjectiveImage.new
  end

  # GET /objective_images/1/edit
  def edit
  end

  # POST /objective_images
  # POST /objective_images.json
  def create
    @objective_image = ObjectiveImage.new(objective_image_params)

    respond_to do |format|
      if @objective_image.save
        format.html { redirect_to @objective_image, notice: 'Objective image was successfully created.' }
        format.json { render :show, status: :created, location: @objective_image }
      else
        format.html { render :new }
        format.json { render json: @objective_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objective_images/1
  # PATCH/PUT /objective_images/1.json
  def update
    respond_to do |format|
      if @objective_image.update(objective_image_params)
        format.html { redirect_to @objective_image, notice: 'Objective image was successfully updated.' }
        format.json { render :show, status: :ok, location: @objective_image }
      else
        format.html { render :edit }
        format.json { render json: @objective_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objective_images/1
  # DELETE /objective_images/1.json
  def destroy
    @objective_image.destroy
    respond_to do |format|
      format.html { redirect_to objective_images_url, notice: 'Objective image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objective_image
      @objective_image = ObjectiveImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objective_image_params
      params.require(:objective_image).permit(:lesson, :statement, :aimg, :bimg, :cimg)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/objective_images_helper.rb
module ObjectiveImagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/objective_images/_form.html.erb
<%= form_for(@objective_image) do |f| %>
  <% if @objective_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@objective_image.errors.count, "error") %> prohibited this objective_image from being saved:</h2>

      <ul>
      <% @objective_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lesson %><br>
    <%= f.text_field :lesson %>
  </div>
  <div class="field">
    <%= f.label :statement %><br>
    <%= f.text_field :statement %>
  </div>
  <div class="field">
    <%= f.label :aimg %><br>
    <%= f.text_field :aimg %>
  </div>
  <div class="field">
    <%= f.label :bimg %><br>
    <%= f.text_field :bimg %>
  </div>
  <div class="field">
    <%= f.label :cimg %><br>
    <%= f.text_field :cimg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/objective_images/edit.html.erb
<h1>Editing Objective Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @objective_image %> |
<%= link_to 'Back', objective_images_path %>

app/views/objective_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Objective Images</h1>

<table>
  <thead>
    <tr>
      <th>Lesson</th>
      <th>Statement</th>
      <th>Aimg</th>
      <th>Bimg</th>
      <th>Cimg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @objective_images.each do |objective_image| %>
      <tr>
        <td><%= objective_image.lesson %></td>
        <td><%= objective_image.statement %></td>
        <td><%= objective_image.aimg %></td>
        <td><%= objective_image.bimg %></td>
        <td><%= objective_image.cimg %></td>
        <td><%= link_to 'Show', objective_image %></td>
        <td><%= link_to 'Edit', edit_objective_image_path(objective_image) %></td>
        <td><%= link_to 'Destroy', objective_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Objective image', new_objective_image_path %>

app/views/objective_images/new.html.erb
<h1>New Objective Image</h1>

<%= render 'form' %>

<%= link_to 'Back', objective_images_path %>

app/views/objective_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lesson:</strong>
  <%= @objective_image.lesson %>
</p>

<p>
  <strong>Statement:</strong>
  <%= @objective_image.statement %>
</p>

<p>
  <strong>Aimg:</strong>
  <%= @objective_image.aimg %>
</p>

<p>
  <strong>Bimg:</strong>
  <%= @objective_image.bimg %>
</p>

<p>
  <strong>Cimg:</strong>
  <%= @objective_image.cimg %>
</p>

<%= link_to 'Edit', edit_objective_image_path(@objective_image) %> |
<%= link_to 'Back', objective_images_path %>